#coding=utf-8
import time
from selenium import webdriver

class sp():

    def __init__(self):
        self.url='http://admina.yjdtest.cn/'
        self.jkr='15896302548'
    def sp123(self):
        driver = webdriver.Chrome()
        # 登录
        driver.get(self.url)
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='username']").send_keys('admin')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='password']").send_keys('123456')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@type='submit']").click()
        time.sleep(4)
        driver.find_element_by_xpath("//a[@data-id='nav_5']").click()
        # 初审
        time.sleep(3)
        driver.find_element_by_xpath("//a[@data-id='VerifyNo1_80']").click()
        time.sleep(2)
        driver.switch_to.frame("iframe_VerifyNo1_80")
        driver.find_element_by_xpath('/html/body/div/form/div[1]/table/tbody/tr[1]/td[10]/a').click()
        time.sleep(2)
        driver.find_element_by_xpath("/html/body/div/div[2]/ul/li[9]/a").click()
        time.sleep(2)
        driver.find_element_by_xpath('/html/body/div/div[2]/ul/li[9]/a').click()
        time.sleep(1)
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[5]/td/ul/li[1]/label/input').click()
        time.sleep(1)
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[8]/td/ul/li[1]/label/input').click()
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[9]/td/textarea').send_keys(
            'sssssssssssssssssssssssssssssssssssssssssssssssssssssss')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[1]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[2]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[3]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[6]/table/tbody/tr[3]/td/textarea').send_keys('okokok')
        driver.find_element_by_xpath('/html/body/div/form/div[7]/div/button').click()
        print u'初审成功'
        time.sleep(3)
        driver.switch_to.default_content()
        # 复审
        driver.find_element_by_xpath('//*[@id="B_menubar"]/dt[17]/a').click()
        time.sleep(2)
        driver.switch_to.frame(driver.find_element_by_xpath('//*[@id="iframe_VerifyNo2_81"]'))
        driver.find_element_by_xpath('/html/body/div/div[3]/table/tbody/tr[1]/td[9]/a').click()
        time.sleep(1)
        driver.find_element_by_xpath('/html/body/div/div[2]/ul/li[7]/a').click()
        time.sleep(1)
        #driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr/td/input').send_keys('15882475913')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[1]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[2]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[3]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[8]/table/tbody/tr[3]/td/textarea').send_keys('ok')
        driver.find_element_by_xpath('/html/body/div/form/div[8]/table/tbody/tr[4]/td/textarea').send_keys('ok')
        driver.find_element_by_xpath('/html/body/div/form/div[9]/div/button').click()
        print u'复审成功'
        time.sleep(3)
        driver.switch_to.default_content()
        # 发标
        driver.find_element_by_xpath('//*[@id="B_menubar"]/dt[18]/a').click()
        time.sleep(1)
        driver.switch_to.frame("iframe_VerifyNo3_94")
        driver.find_element_by_xpath('/html/body/div/div[1]/table/tbody/tr[1]/td[9]/a').click()
        time.sleep(2)
        driver.find_element_by_xpath('/html/body/div[1]/div[2]/ul/li[7]/a').click()
        time.sleep(2)
        jjs = "$('input:radio').eq(7).attr('checked', 'checked').click()"
        driver.execute_script(jjs)
        driver.find_element_by_xpath('/html/body/div[1]/form/div[4]/table/tbody/tr[3]/td/textarea').send_keys('ok')
        driver.find_element_by_xpath('/html/body/div[1]/form/div[5]/div/button').click()
        print u'发标成功'
        time.sleep(1)
        driver.quit()
        #取borrow_id
    def borrow(self):
        driver1 = webdriver.Chrome()
        driver1.get(self.url)
        time.sleep(2)
        driver1.find_element_by_xpath("//input[@id='username']").send_keys('admin')
        time.sleep(2)
        driver1.find_element_by_xpath("//input[@id='password']").send_keys('123456')
        time.sleep(2)
        driver1.find_element_by_xpath("//input[@type='submit']").click()
        time.sleep(4)
        driver1.find_element_by_xpath("//*[@id='J_B_main_block']/li[5]/a").click()
        time.sleep(1)
        driver1.find_element_by_xpath('//*[@id="B_menubar"]/dt[15]/a').click()
        time.sleep(2)
        driver1.switch_to.frame('iframe_Borrow_79')
        s = driver1.find_element_by_xpath('/html/body/div/div[3]/table/tbody/tr[1]/td[1]').text
        driver1.quit()
        return int(s)
    def maxsp(self):
        driver2 = webdriver.Chrome()
        # 登录
        driver2.get(self.url)
        time.sleep(2)
        driver2.find_element_by_xpath("//input[@id='username']").send_keys('admin')
        time.sleep(2)
        driver2.find_element_by_xpath("//input[@id='password']").send_keys('123456')
        time.sleep(2)
        driver2.find_element_by_xpath("//input[@type='submit']").click()
        time.sleep(4)
        driver2.find_element_by_xpath("//a[@data-id='nav_5']").click()
        time.sleep(2)
        driver2.find_element_by_xpath('//*[@id="B_menubar"]/dt[19]/a').click()
        time.sleep(2)
        driver2.switch_to.frame('iframe_VerifyNo4_82')
        driver2.find_element_by_xpath('/html/body/div/div[1]/table/tbody/tr[1]/td[9]/a').click()
        time.sleep(2)
        driver2.find_element_by_xpath('/html/body/div/div[2]/ul/li[7]/a').click()
        time.sleep(2)
        driver2.find_element_by_xpath('/html/body/div/form/div[8]/table/tbody/tr[2]/td/textarea').send_keys('okokok')
        driver2.find_element_by_xpath('/html/body/div/form/div[9]/div/button').click()
        time.sleep(8)
        print u'终审成功'
        driver2.quit()
    def second_sp123(self):
        #添加发标时间的审批
        driver = webdriver.Chrome()
        # 登录
        driver.get(self.url)
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='username']").send_keys('admin')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='password']").send_keys('123456')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@type='submit']").click()
        time.sleep(4)
        driver.find_element_by_xpath("//a[@data-id='nav_5']").click()
        # 初审
        time.sleep(3)
        driver.find_element_by_xpath("//a[@data-id='VerifyNo1_80']").click()
        time.sleep(2)
        driver.switch_to.frame("iframe_VerifyNo1_80")
        driver.find_element_by_xpath('/html/body/div/form/div[1]/table/tbody/tr[1]/td[10]/a').click()
        time.sleep(2)
        driver.find_element_by_xpath("/html/body/div/div[2]/ul/li[9]/a").click()
        time.sleep(2)
        driver.find_element_by_xpath('/html/body/div/div[2]/ul/li[9]/a').click()
        time.sleep(1)
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[5]/td/ul/li[1]/label/input').click()
        time.sleep(1)
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[8]/td/ul/li[1]/label/input').click()
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[9]/td/textarea').send_keys(
            'sssssssssssssssssssssssssssssssssssssssssssssssssssssss')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[1]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[2]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[3]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[6]/table/tbody/tr[3]/td/textarea').send_keys('okokok')
        driver.find_element_by_xpath('/html/body/div/form/div[7]/div/button').click()
        print u'初审成功'
        time.sleep(3)
        driver.switch_to.default_content()
        # 复审
        driver.find_element_by_xpath('//*[@id="B_menubar"]/dt[17]/a').click()
        time.sleep(2)
        driver.switch_to.frame(driver.find_element_by_xpath('//*[@id="iframe_VerifyNo2_81"]'))
        driver.find_element_by_xpath('/html/body/div/div[3]/table/tbody/tr[1]/td[9]/a').click()
        time.sleep(1)
        driver.find_element_by_xpath('/html/body/div/div[2]/ul/li[7]/a').click()
        time.sleep(1)
        # driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr/td/input').send_keys('15882475913')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[1]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[2]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[4]/table/tbody/tr[3]/td/input').send_keys('100')
        driver.find_element_by_xpath('/html/body/div/form/div[8]/table/tbody/tr[3]/td/textarea').send_keys('ok')
        driver.find_element_by_xpath('/html/body/div/form/div[8]/table/tbody/tr[4]/td/textarea').send_keys('ok')
        driver.find_element_by_xpath('/html/body/div/form/div[9]/div/button').click()
        print u'复审成功'
        time.sleep(3)
        driver.switch_to.default_content()
        # 发标
        driver.find_element_by_xpath('//*[@id="B_menubar"]/dt[18]/a').click()
        time.sleep(1)
        driver.switch_to.frame("iframe_VerifyNo3_94")
        driver.find_element_by_xpath('/html/body/div/div[1]/table/tbody/tr[1]/td[9]/a').click()
        time.sleep(2)
        driver.find_element_by_xpath('/html/body/div[1]/div[2]/ul/li[7]/a').click()
        time.sleep(2)
        jjs = "$('input:radio').eq(7).attr('checked', 'checked').click()"
        driver.execute_script(jjs)
        future_time=str(int(time.strftime('%M'))+3)#定义需要设置的分钟数,比当前多三分钟
        driver.find_element_by_xpath('/html/body/div[1]/form/div[2]/table/tbody/tr[4]/td/input').click()#点击开始投标时间
        driver.find_element_by_xpath('//*[@id="calMin"]').clear()
        driver.find_element_by_xpath('//*[@id="calMin"]').send_keys(future_time)
        driver.find_element_by_xpath('//*[@id="calbody"]/div[3]/button').click()
        driver.find_element_by_xpath('/html/body/div[1]/form/div[4]/table/tbody/tr[3]/td/textarea').send_keys('ok')
        driver.find_element_by_xpath('/html/body/div[1]/form/div[5]/div/button').click()
        print u'发标成功'
        time.sleep(1)
        driver.quit()
    def dianfu(self):
        driver=webdriver.Chrome()
        driver.get(self.url)
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='username']").send_keys('admin')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='password']").send_keys('123456')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@type='submit']").click()
        time.sleep(4)
        driver.find_element_by_xpath("//a[@data-id='nav_5']").click()
        #点击财务
        driver.find_element_by_xpath('//*[@id="J_B_main_block"]/li[8]/a').click()
        time.sleep(2)
        driver.find_element_by_xpath('//*[@id="B_menubar"]/dt[7]/a').click()#点击逾期垫付
        driver.switch_to.frame("iframe_Overdue_43")
        driver.find_element_by_xpath('//*[@id="search_form"]/input[1]').send_keys(self.jkr)
        driver.find_element_by_xpath('//*[@id="search_form"]/button').click()
        driver.implicitly_wait(10)
        #点击垫付确定
        driver.find_element_by_xpath('/html/body/div/div[3]/table/tbody/tr/td[6]/ul/li/a').click()
        driver.find_element_by_xpath('/html/body/div[1]/div/table/tbody/tr[2]/td[2]/div/table/tbody/tr[3]/td/div/input[1]').click()
        driver.quit()
    def tixian(self):
        driver=webdriver.Chrome()
        driver.get('https://u.yjdtest.cn/test?mobile='+self.jkr)
        driver.implicitly_wait(10)
        driver.find_element_by_xpath('/html/body/div[2]/div/div[2]/a').click()
        cash=driver.find_element_by_xpath('//*[@id="user-right"]/div[4]/div/div[1]/div/div[2]/font').text
        if len(cash)>=8:
            cash=str(cash).replace(',','')
        else:
            cash=str(cash)
        print cash
        driver.find_element_by_xpath('//*[@id="user-right"]/div[4]/div/div[1]/div/div[1]/a[2]').click()
        time.sleep(10)
        driver.find_element_by_xpath('//*[@id="user-right"]/div[4]/div/div[1]/div/div[1]/a[2]').click()
        driver.find_element_by_xpath('//*[@id="price"]').click()
        driver.find_element_by_xpath('//*[@id="price"]').send_keys(cash)
        driver.find_element_by_xpath('//*[@id="J_ajax_submit_btn"]').click()
        time.sleep(5)
        driver.find_element_by_xpath('//*[@id="e_hr_getMsgCode"]').click()
        driver2=webdriver.Chrome()
        driver2.get('http://203.110.167.196:9082/usercenter/msgCode.html')
        driver2.implicitly_wait(10)
        driver2.find_element_by_xpath('//*[@id="verificationCode_txt"]').send_keys(self.jkr)
        driver2.find_element_by_xpath('//*[@id="verificationCode_btn"]').click()
        yzm=driver2.find_element_by_xpath('//*[@id="verificactionCode"]/tbody/tr/td[3]').text
        yzm=str(yzm)
        driver.find_element_by_xpath('//*[@id="e_hr_msgCode"]').send_keys(yzm)
        driver.find_element_by_xpath('//*[@id="hr_fake_pwd1"]').click()
        for i in range(6):
            driver.find_element_by_xpath('//*[@id="NumberKeyboard___100"]').click()
        driver.find_element_by_xpath('//*[@id="hr_modal_footer"]/button[2]').click()
        driver.quit()
        driver2.quit()
    def chongzhi(self):
        driver=webdriver.Chrome()
        driver.get(self.url)
        driver.find_element_by_xpath("//input[@id='username']").send_keys('admin')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@id='password']").send_keys('123456')
        time.sleep(2)
        driver.find_element_by_xpath("//input[@type='submit']").click()
        time.sleep(4)
        driver.find_element_by_xpath('//*[@id="J_B_main_block"]/li[8]/a').click()
        driver.implicitly_wait(10)
        driver.find_element_by_xpath('//*[@id="B_menubar"]/dt[8]/a').click()
        driver.switch_to.frame('iframe_Money_46')
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[1]/td/input').send_keys('m_'+self.jkr)
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[3]/td/input').send_keys('200')
        driver.find_element_by_xpath('/html/body/div/form/div[2]/table/tbody/tr[4]/td/input').send_keys('ddsdsa')
        driver.find_element_by_xpath('/html/body/div/form/div[3]/div/button').click()
        driver2=webdriver.Chrome()
        driver2.get('https://u.yjdtest.cn/test?mobile='+self.jkr)
        driver2.find_element_by_xpath('/html/body/div[2]/div/div[2]/a').click()
        driver2.implicitly_wait(10)
        driver2.find_element_by_xpath('//*[@id="Depotransfer"]').click()
        driver2.find_element_by_xpath('/html/body/div[10]/div/table/tbody/tr[3]/td/div[2]/button[2]').click()
        time.sleep(5)
        driver.quit()
        driver2.quit()
if __name__ == '__main__':
    x=sp()
    x.chongzhi()